name: Transform Marc Records
on: [push]
jobs:
  Run-Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13.3'
      - name: Install pymarc
        run: pip install pymarc
      - name: Transform from marcxml to mrc
        run: python 1-convert-xml-to-marc.py
      - name: Update records
        run: python 2-update-marc-records.py
      - name: Validate records
        run: python 3-validate-marc-records.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
